# Generated by Django 3.2 on 2021-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physique',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du diagnostic'),
        ),
    ]
