# Generated by Django 3.2 on 2021-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0002_alter_physique_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physique',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date du diagnostic'),
        ),
    ]
