# Generated by Django 3.2 on 2021-05-04 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0003_alter_physique_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physique',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du diagnostic'),
        ),
    ]
