# Generated by Django 3.2 on 2021-05-04 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0004_alter_physique_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du test'),
        ),
    ]
