# Generated by Django 3.2 on 2021-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0005_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='peri_marche',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='durée maximale de marche estimée par la personne (durée en min / heures)', verbose_name='Périmétrage de marche min/heures (facultatif)'),
        ),
    ]
