# Generated by Django 3.2 on 2021-05-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0006_alter_test_peri_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='chute_annuel',
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Chutes dans l'année"),
        ),
    ]
