# Generated by Django 3.2 on 2021-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0007_alter_beneficiaire_chute_annuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='peri_marche',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='durée maximale de marche estimée par la personne (durée en min / heures)', verbose_name='Périmétrage de marche en minutes (facultatif)'),
        ),
    ]
