# Generated by Django 3.2 on 2021-05-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyma', '0008_alter_test_peri_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='appartement',
            field=models.PositiveIntegerField(verbose_name="Numéro d'appartement"),
        ),
    ]
